whoohoo/about/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('about.views',
    url(r'^$', 'about', name='about'),
    url(r'^(?P<profile_slug>[\w-]+)/$', 'profile', name='about_profile'),
)

whoohoo/portfolio/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('portfolio.views',
    url(r'^$', 'portfolio', name='portfolio'),
    url(r'^tag/(?P<tag_slug>[\w-]+)/$', 'portfolio', name='portfolio_tag'),
    url(r'^(?P<client_slug>[\w-]+)/$', 'client', name='portfolio_client'),
    url(r'^(?P<client_slug>[\w-]+)/(?P<project_slug>[\w-]+)/$', 'project', name='portfolio_project'),
    # url(r'^whoohoo/', include('whoohoo.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

whoohoo/whoohoo/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'whoohoo.views.home', name='home'),
    url(r'^contact/$', 'whoohoo.views.contact', name='contact'),
    url(r'^reel/$', 'whoohoo.views.reel', name='reel'),
    url(r'^about/', include('about.urls')),
    url(r'^portfolio/', include('portfolio.urls')),
    url(r'^terms-and-conditions/$', 'whoohoo.views.terms', name='terms'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

whoohoo/portfolio/models.py
from django.db import models

from utils.storage import OverwriteStorage

import os
import markdown
import sorl


class Client(models.Model):
    def file_path(instance, filename):
        filename, ext = os.path.splitext(filename)
        filename = 'logo' + ext
        return os.path.join('portfolio/{client}'.format(client=instance.slug), filename)

    STATUS_OFFLINE = 0
    STATUS_PRIVATE = 1
    STATUS_ONLINE = 2

    __STATUS_CHOICES = ((STATUS_PRIVATE, u'prive'),
                        (STATUS_ONLINE, u'online'),
                        (STATUS_OFFLINE, u'offline'), )

    name = models.CharField(u'klantnaam', max_length=250, unique=True)
    slug = models.SlugField(u'slug', max_length=100, unique=True)
    logo = models.ImageField(u'logo', storage=OverwriteStorage(), upload_to=file_path, blank=True)
    url = models.URLField(u'URL', null=True, blank=True)
    desc = models.TextField(u'omschrijving', null=True, blank=True)
    desc_html = models.TextField(u'html omschrijving', null=True, blank=True, editable=False)
    status = models.PositiveIntegerField(u'status', choices=__STATUS_CHOICES)

    class Meta:
        ordering = ['name', 'status']
        verbose_name = "klant"
        verbose_name_plural = "klanten"

    def save(self, *args, **kwargs):
        if self.logo:
            sorl.thumbnail.delete(self.logo, delete_file=False)

        self.desc_html = markdown.markdown(self.desc, extensions=['extra', 'nl2br', 'sane_lists'], output_format='html5')
        super(Client, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'{0}'.format(self.name)


class Project(models.Model):
    STATUS_OFFLINE = 0
    STATUS_PRIVATE = 1
    STATUS_ONLINE = 2

    __STATUS_CHOICES = ((STATUS_PRIVATE, u'prive'),
                        (STATUS_ONLINE, u'online'),
                        (STATUS_OFFLINE, u'offline'), )

    def thumbnail_path(instance, filename):
        filename, ext = os.path.splitext(filename)
        filename = 'thumbnail' + ext
        return os.path.join('portfolio/{client}/{project}'.format(client=instance.client.slug, project=instance.slug), filename)

    def background_path(instance, filename):
        filename, ext = os.path.splitext(filename)
        filename = 'background' + ext
        return os.path.join('portfolio/{client}/{project}'.format(client=instance.client.slug, project=instance.slug), filename)

    client = models.ForeignKey('Client', verbose_name='klant')
    title = models.CharField(u'projecttitel', max_length=100, unique=True)
    slug = models.SlugField(u'slug', max_length=100, unique=True)
    date = models.DateField(u'datum')
    thumbnail = models.ImageField(u'thumbnail', storage=OverwriteStorage(), upload_to=thumbnail_path, blank=True, help_text=u'Afbeelding verhouding 16:9')
    background = models.ImageField(u'achtergrond', storage=OverwriteStorage(), upload_to=background_path, blank=True, help_text=u'Afbeelding verhouding 16:9')
    desc = models.TextField(u'omschrijving', null=True, blank=True)
    desc_html = models.TextField(u'html omschrijving', null=True, blank=True, editable=False)
    vimeo = models.CharField(u'vimeo id', max_length=20, null=True, blank=True)
    url = models.URLField(u'URL', null=True, blank=True)
    status = models.PositiveIntegerField(u'status', choices=__STATUS_CHOICES)
    tags = models.ManyToManyField('Tag', verbose_name='label')

    class Meta:
        verbose_name = 'project'
        verbose_name_plural = 'projecten'
        ordering = ['-date', 'title']

    def client_name(self):
        return self.client.name
    client_name.short_description = 'klantnaam'

    def save(self, *args, **kwargs):
        if self.thumbnail:
            sorl.thumbnail.delete(self.thumbnail, delete_file=False)
        if self.background:
            sorl.thumbnail.delete(self.background, delete_file=False)

        self.desc_html = markdown.markdown(self.desc, extensions=['extra', 'nl2br', 'sane_lists'], output_format='html5')
        super(Project, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'{0}: {1} ({2})'.format(self.client.name, self.title, self.get_status_display())


class Still(models.Model):
    def file_path(instance, filename):
        return os.path.join('portfolio/{client}/{project}'.format(client=instance.project.client.slug, project=instance.project.slug), filename)

    title = models.CharField(u'titel', max_length=250)
    project = models.ForeignKey('Project', verbose_name='project')
    image = models.ImageField(u'afbeelding', storage=OverwriteStorage(), upload_to=file_path, blank=True)

    class Meta:
        verbose_name = 'still'
        verbose_name_plural = 'stills'
        ordering = ['title']

    def project_title(self):
        return self.project.title
    project_title.short_description = 'projecttitel'

    def save(self, *args, **kwargs):
        if self.image:
            sorl.thumbnail.delete(self.image, delete_file=False)

        super(Still, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'{0}: {1} ({2})'.format(self.project.title, self.title, self.image.name)


class Tag(models.Model):
    name = models.CharField(u'label', max_length=100)
    slug = models.SlugField(u'slug', max_length=100, unique=True)
    priority = models.PositiveIntegerField(u'prioriteit', help_text=u'Rangschikking op prioriteit, 1 staat bovenaan.')

    class Meta:
        verbose_name = 'label'
        verbose_name_plural = 'labels'
        ordering = ['name']

    def __unicode__(self):
        return self.name

'''
class RootBlock(models.Model):
    SIZE_1 = 1
    SIZE_2 = 2
    SIZE_3 = 3

    __SIZE_CHOICES = ((SIZE_1, u'250 pixels'),
                      (SIZE_2, u'500 pixels'),
                      (SIZE_3, u'750 pixels'), )

    width = models.PositiveIntegerField(u'breedte', choices=__SIZE_CHOICES)
    position = models.PositiveIntegerField(u'positie')

class Block(models.Model):
    SIZE_1 = 1
    SIZE_2 = 2
    SIZE_3 = 3

    __SIZE_CHOICES = ((SIZE_1, u'250 pixels'),
                      (SIZE_2, u'500 pixels'),
                      (SIZE_3, u'750 pixels'), )

    width = models.PositiveIntegerField(u'breedte', choices=__SIZE_CHOICES)
    height = models.PositiveIntegerField(u'hoogte', choices=__SIZE_CHOICES)
    project = models.ForeignKey('Project', verbose_name='project')
    position = models.PositiveIntegerField(u'positie')
'''

whoohoo/portfolio/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

from portfolio.models import Client, Project, Tag


def portfolio(request, tag_slug=None):
    tags = Tag.objects.all().order_by('priority')

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        portfolio = Project.objects.filter(status=Project.STATUS_ONLINE, tags=tag).order_by('-date')
        tag_selected = tag.slug
    else:
        portfolio = Project.objects.filter(status=Project.STATUS_ONLINE).order_by('-date')
        tag_selected = None

    return render_to_response('portfolio/portfolio.html',
                              {'selectnav': 'portfolio',
                               'tags': tags,
                               'tag_selected': tag_selected,
                               'portfolio': portfolio, }, RequestContext(request))


def client(request, client_slug):
    client = get_object_or_404(Client, slug=client_slug, status=Client.STATUS_ONLINE)

    return render_to_response('portfolio/client.html',
                              {'selectnav': 'portfolio',
                               'client': client, }, RequestContext(request))


def project(request, client_slug, project_slug):
    portfolio = Project.objects.filter(status=Project.STATUS_ONLINE)
    project = get_object_or_404(Project, client__slug=client_slug, slug=project_slug, status__in=[Project.STATUS_ONLINE, Project.STATUS_PRIVATE])

    return render_to_response('portfolio/project.html',
                              {'selectnav': 'portfolio',
                               'portfolio': portfolio,
                               'project': project, }, RequestContext(request))

whoohoo/portfolio/templates/portfolio/client.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{ client.name }} {{ block.super }}{% endblock %}
{% block content %}
<div class="client">
    <h1>{{ client.name }}</h1>
    {% thumbnail client.logo "320x180" crop="center" as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ client.name }} logo">
    {% endthumbnail %}
    {{ client.desc_html|safe }}
</div>
{% endblock %}

whoohoo/portfolio/templates/portfolio/portfolio.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %}Portfolio {{ block.super }}{% endblock %}
{% block meta %}
    <meta name="description" content="An overview of WhooHoo's stunning projects.">
{% endblock %}
{% block bgmedia %}
    <div id="media">
        <div style="background: url({% static 'img/vanrossum.jpg' %}) no-repeat center center; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;"></div>
    </div>
    <div id="grain"></div>
{% endblock %}
{% block content %}
<div class="portfolio">
    <nav class="filters">
        <ul>
            <li><a {% if not tag_selected %}class="selected"{% endif %} href="{% url 'portfolio' %}">All</a></li>
            {% for tag in tags %}
                <li><a {% if tag.slug == tag_selected %}class="selected"{% endif %} href="{% url 'portfolio_tag' tag_slug=tag.slug %}">{{ tag.name }}</a></li>
            {% endfor %}
        </ul>
    </nav>
    <div class="clear"></div>
    <div class="portfolio-wrapper">
        {% for item in portfolio %}
            <a class="project-thumbnail" id="item-{{ forloop.counter }}" href="{% url 'portfolio_project' client_slug=item.client.slug project_slug=item.slug %}">
                {% if item.thumbnail %}
                    {% thumbnail item.thumbnail "320x180" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" data-large="{{ MEDIA_URL }}{{ item.background }}">
                    {% endthumbnail %}
                {% else %}
                    <img src="{% static 'img/studio-whoohoo-logo.png' %}" width="320" height="180" data-large="{% static 'img/studio-whoohoo-logo.png' %}">
                {% endif %}
                <div class="title">{{ item.title }}</div>
            </a>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block javascript %}
    <script src="{% static 'js/swap-background.js' %}"></script>
    <script>
    {# Swap background when hovering over thumbnails #}
    $('.project-thumbnail img').hover(
        function(){
            if($(this).attr('data-large') != $('#background #media div:first').attr('data-large')){
                swap_background(bg=$(this).attr('data-large'));
            }
        },
        function(){}
    );
    </script>
{% endblock %}

whoohoo/portfolio/templates/portfolio/project.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %}{{ project.title }} {{ block.super }}{% endblock %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'plugins/fancyBox-2.1.5/jquery.fancybox.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'plugins/FlexSlider-2.2.2/flexslider.css' %}" type="text/css" media="screen">
{% endblock %}
{% block bgmedia %}
    <div id="media">
        <div style="background: url({{ MEDIA_URL }}{{ project.background }}) no-repeat center center; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;"></div>
    </div>
    <div id="grain"></div>
{% endblock %}
{% block content %}
    <div class="container">
        {% if project.vimeo %}
            <div class="videoplayer">
                <iframe src="//player.vimeo.com/video/{{ project.vimeo }}" width="1000" height="562" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </div>
        {% else %}
            <div class="video-placeholder">
                {% thumbnail project.thumbnail "1000x562" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="vimeo-placeholder">
                {% endthumbnail %}
            </div>
        {% endif %}
    </div>
    <div class="content">
        <div class="container">
            <h1>{{ project.title }}</h1>
            <div class="project_date lightgray-text">{{ project.date|date:"d.m.y" }}</div>
            <div class="project_description{% if not project.still_set.all %}full{% endif %}">
                {{ project.desc_html|safe }}
            </div>
            {% if project.still_set.all %}
                <div class="project_stills">
                    {% for still in project.still_set.all %}
                        {% thumbnail still.image "302x170" crop="center" as im %}
                            <a class="fancybox" rel="{{ project.title }}" href="{{ MEDIA_URL }}{{ still.image }}" title="{{ still.title }}">
                                <img src="{{ im.url }}" alt="{{ project.name }} logo" title="{{ still.title }}">
                            </a>
                            {% cycle '' '<div class="clear"></div>' %}
                        {% endthumbnail %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div  id="slider" class="flexslider project_carousel">
            <ul class="slides">
            {% for item in portfolio %}
                <li>
                    <a class="item" id="item-{{ forloop.counter }}" href="{% url 'portfolio_project' client_slug=item.client.slug project_slug=item.slug %}">
                    {% if item.thumbnail %}
                        {% thumbnail item.thumbnail "267x150" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% endthumbnail %}
                    {% endif %}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script src="{% static 'plugins/fancyBox-2.1.5/jquery.fancybox.pack.js' %}"></script>
    <script type="text/javascript">
        {# Settings for the lightbox #}
        $(document).ready(function() {
            $(".fancybox").fancybox({'padding': 3});
        });
    </script>
    <script defer src="{% static 'plugins/FlexSlider-2.2.2/jquery.flexslider-min.js' %}"></script>
    <script>
        {# Settings for the sliding gallery #}
        $(window).load(function() {
          $('.flexslider').flexslider({
            namespace: "flex-",
            animation: "slide", // fade
            easing: "swing",
            slideshow: false,
            animationLoop: true,
            directionNav: true,
            controlNav: false,
            itemWidth: 267,
            itemMargin: 0,
          });
        });
    </script>
{% endblock %}